export const data = JSON.parse("{\"key\":\"v-672d5762\",\"path\":\"/tool/Git/Git.html\",\"title\":\"Git版本管理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Git版本管理\",\"date\":\"2018-06-27T00:00:00.000Z\",\"category\":[\"工具\"],\"tag\":[\"git\"],\"summary\":\"Git 是目前世界上最先进的分布式版本控制系统\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/igarashi-blog/igarashi-blog/tool/Git/Git.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Git版本管理\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"git\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2018-06-27T00:00:00.000Z\"}]]},\"excerpt\":\"<p><strong>Git</strong> 是目前世界上最先进的分布式版本控制系统</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. 基础部分\",\"slug\":\"_1-基础部分\",\"link\":\"#_1-基础部分\",\"children\":[{\"level\":3,\"title\":\"1.1 安装\",\"slug\":\"_1-1-安装\",\"link\":\"#_1-1-安装\",\"children\":[]},{\"level\":3,\"title\":\"1.2 配置\",\"slug\":\"_1-2-配置\",\"link\":\"#_1-2-配置\",\"children\":[]},{\"level\":3,\"title\":\"1.3. 获取 Git 帮助\",\"slug\":\"_1-3-获取-git-帮助\",\"link\":\"#_1-3-获取-git-帮助\",\"children\":[]},{\"level\":3,\"title\":\"1.4 创建一个版本库 - 步骤\",\"slug\":\"_1-4-创建一个版本库-步骤\",\"link\":\"#_1-4-创建一个版本库-步骤\",\"children\":[]}]},{\"level\":2,\"title\":\"2 进阶部分\",\"slug\":\"_2-进阶部分\",\"link\":\"#_2-进阶部分\",\"children\":[{\"level\":3,\"title\":\"2.1 撤销\",\"slug\":\"_2-1-撤销\",\"link\":\"#_2-1-撤销\",\"children\":[]},{\"level\":3,\"title\":\"2.2 删除\",\"slug\":\"_2-2-删除\",\"link\":\"#_2-2-删除\",\"children\":[]},{\"level\":3,\"title\":\"2.3 其他内容\",\"slug\":\"_2-3-其他内容\",\"link\":\"#_2-3-其他内容\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 分支管理\",\"slug\":\"_3-分支管理\",\"link\":\"#_3-分支管理\",\"children\":[{\"level\":3,\"title\":\"3.1 基本操作\",\"slug\":\"_3-1-基本操作\",\"link\":\"#_3-1-基本操作\",\"children\":[]},{\"level\":3,\"title\":\"3.2 解决冲突\",\"slug\":\"_3-2-解决冲突\",\"link\":\"#_3-2-解决冲突\",\"children\":[]},{\"level\":3,\"title\":\"3.3 分支管理策略\",\"slug\":\"_3-3-分支管理策略\",\"link\":\"#_3-3-分支管理策略\",\"children\":[]}]},{\"level\":2,\"title\":\"4. 标签管理\",\"slug\":\"_4-标签管理\",\"link\":\"#_4-标签管理\",\"children\":[]},{\"level\":2,\"title\":\"5. 远程仓库\",\"slug\":\"_5-远程仓库\",\"link\":\"#_5-远程仓库\",\"children\":[]}],\"readingTime\":{\"minutes\":30.47,\"words\":9142},\"filePathRelative\":\"tool/Git/Git.md\",\"localizedDate\":\"2018年6月27日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
