<template><div><p>快速排查故障、定位问题</p>
<!--more-->
<h2 id="_1-gdb" tabindex="-1"><a class="header-anchor" href="#_1-gdb"><span>1. gdb</span></a></h2>
<p>对于排查进程、线程故障、死循环、死锁、Hung process 等故障，除了用 <a href="https://man7.org/linux/man-pages/man1/strace.1.html" target="_blank" rel="noopener noreferrer">strace</a> 跟一下系统调用来猜原因，相比之下用 <strong>gdb</strong> 来打印 <strong>C</strong> 的堆栈信息，更加有说服力和说明问题</p>
<h3 id="_1-1-安装" tabindex="-1"><a class="header-anchor" href="#_1-1-安装"><span>1.1 安装</span></a></h3>
<p>首先得有 <a href="https://man7.org/linux/man-pages/man1/gdb.1.html" target="_blank" rel="noopener noreferrer">gdb</a> 才能查</p>
<Tabs id="16" :data='[{"id":"CentOS"},{"id":"Debian"}]'>
<template #title0="{ value, isActive }">CentOS</template>
<template #title1="{ value, isActive }">Debian</template>
<template #tab0="{ value, isActive }">
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> yum</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -y</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> yum-utils</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> debuginfo-install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> glibc</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 会出现如下包的提示</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Package</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                                Arch</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        Version</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">               Repository</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">           Size</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">====================================================================================================</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Installing:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> glibc-debuginfo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                        x86_64</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      2.17-326.el7_9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        base-debuginfo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">      9.5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> nss-softokn-debuginfo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                  x86_64</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      3.44.0-8.el7_7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        base-debuginfo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">      2.1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> yum-plugin-auto-update-debug-info</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      noarch</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      1.1.31-54.el7_8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       base</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 29</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> k</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Installing</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dependencies:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> glibc-debuginfo-common</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                 x86_64</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      2.17-326.el7_9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        base-debuginfo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">      9.7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>若报错，则需要执行如下改动</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 不存在该文件则创建，有则改写如下</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /etc/yum.repos.d/CentOS-Debuginfo.repo</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[base-debuginfo]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">CentOS-7</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> -</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Debuginfo</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">baseurl</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">http://debuginfo.centos.org/7/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$basearch</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">/</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gpgcheck</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">1</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gpgkey</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Debug-7</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> enabled=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">+</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> enabled=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后再安装 <strong>gdb</strong></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 安装 gdb python3-debuginfo 注意是 python3</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">yum</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -y</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python3-debuginfo</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>执行 <code v-pre>gdb python</code></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python3</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GNU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (GDB) Red Hat Enterprise Linux 7.6.1-120.el7</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Copyright</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (C) 2013 Free Software Foundation, Inc.</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">License</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> GPLv3+:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> GNU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> GPL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> version</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> later</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">http://gnu.org/licenses/gpl.htm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">l></span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> symbols</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /opt/miniconda3/bin/python3.9...done.</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 注意最后的版本号</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apt-get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python3-dbg</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>还需要装一个包  <code v-pre>python3-dbg</code> ， 这个包有什么作用呢？ 前面不是抱怨过 <code v-pre>C</code> 堆栈对于调试一个 <code v-pre>Python</code> 有何用？ 我们更需要的是 <code v-pre>Python</code> 堆栈信息， <code v-pre>python-dbg</code> 就是为了完成这个使命</p>
</template>
</Tabs>
<h3 id="_1-2-运行" tabindex="-1"><a class="header-anchor" href="#_1-2-运行"><span>1.2 运行</span></a></h3>
<p>全新启动一个 <code v-pre>Python</code> 程序并进行调试，可以采用交互式方式， 先启动 <a href="https://man7.org/linux/man-pages/man1/gdb.1.html" target="_blank" rel="noopener noreferrer">gdb</a> 然后在 <code v-pre>gdb shell</code> 中启动 <code v-pre>Python</code> 程序</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 启动 </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">...</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">run</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">programnam</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">e></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">.py</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">argument</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">s></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 一条命令</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -ex</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> r</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --args</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">programnam</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">e></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">.py</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">argument</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">s></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>正在运行的程序突然异常，需要调试它，若去给它发个信号，出一个 <code v-pre>coredump</code> 文件，然后用 <code v-pre>gdb</code> 来调试 <code v-pre>coredump</code> 文件，像这样</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 调试 coredump 文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">coredump_fil</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">e></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>显然易见，不是种好的方式，若捕获进程调试，效率才高</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 获取 python 进程id</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ps</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -ef</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pstree</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -p</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pid</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> strace</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -p</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pid</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 进入调试</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> python</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -p</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">process</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> i</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">d> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gdb</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> attach</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x3C;</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">process</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> i</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">d></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这两种方式都可以让 <code v-pre>gdb</code> 捕获一个进程。 因此，需要做的只是确定问题进程的 <code v-pre>pid</code> ，如使用 <code v-pre>top</code> 、 <code v-pre>ps</code> 等命令确定 <strong>Python</strong> 进程</p>
<h3 id="_1-3-使用" tabindex="-1"><a class="header-anchor" href="#_1-3-使用"><span>1.3 使用</span></a></h3>
<h4 id="堆栈查看" tabindex="-1"><a class="header-anchor" href="#堆栈查看"><span><strong>堆栈查看</strong></span></a></h4>
<p>查看 <code v-pre>C</code> 堆栈信息使用 <code v-pre>bt</code></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bt</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#0 0x0000002a95b3b705 in raise () from /lib/libc.so.6</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#1 0x0000002a95b3ce8e in abort () from /lib/libc.so.6</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#2 0x00000000004c164f in posix_abort (self=0x0, noargs=0x0) at ../Modules/posixmodule.c:7158</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#3 0x0000000000489fac in call_function (pp_stack=0x7fbffff110, oparg=0) at ../Python/ceval.c:3531</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#4 0x0000000000485fc2 in PyEval_EvalFrame (f=0x66ccd8) at ../Python/ceval.c:2163</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>那么查看 <strong>Python</strong> 堆栈则要在安装 <code v-pre>python-gdb</code> 之后， <code v-pre>gdb</code> 才会提供若干相关的操作</p>
<p>使用 <code v-pre>py-bt</code> 就是用来查看 <code v-pre>Python</code> 堆栈</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (gdb) py-bt</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p>若提示 <code v-pre>Undefined command: &quot;py-bt&quot;. Try &quot;help&quot;</code> ，这多半是 <strong>gdb</strong> 绑定的是老版的 <strong>python2.7</strong>，对于 <strong>CentOS</strong> 需要手动导入 <code v-pre>libpython.py</code> 让 <strong>gdb</strong> 读取（<em><strong>Debian 是 <a href="http://pythonx.x-gdb.py" target="_blank" rel="noopener noreferrer">pythonx.x-gdb.py</a></strong></em> ）</p>
<p>故需手动下载 <a href="https://github.com/python/cpython/blob/master/Tools/gdb/libpython.py" target="_blank" rel="noopener noreferrer">libpython.py</a> 文件到本地</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">wget</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://raw.githubusercontent.com/python/cpython/main/Tools/gdb/libpython.py</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 连不通需要使用自己的代理</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">export</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> all_proxy</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"https://192.168.3.97:7890"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>若 <strong>DNS</strong> 解析失败需，去网站三方工具查 <strong>DNS</strong> ，然后修改 <code v-pre>/etc/hosts</code></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /etc/hosts</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><img src="@source/unix/Linux/Troubleshooting/img/rawgithosts.jpg">  
<p>若需要搜索某些文件，则</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">find</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "*libpython*"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 或安装快速查找工具</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">yum</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -y</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> locate</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 更新数据库</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">updatedb</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查找某些文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">locate</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "*libpython*"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>手动关联 <strong><a href="http://libpython.py" target="_blank" rel="noopener noreferrer">libpython.py</a></strong></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">python</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>import sys</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>sys.path.insert(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "/home/zz/CODE"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>import libpython</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>end</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">py-bt</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Traceback</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (most </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">recent</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> call</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> first</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">...</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><img src="@source/unix/Linux/Troubleshooting/img/py-bt.jpg"> 
</div>
<h4 id="线程查看" tabindex="-1"><a class="header-anchor" href="#线程查看"><span>线程查看</span></a></h4>
<p>调试多线程程序，使用 <code v-pre>info threads</code>，但总得搞清楚到底有哪些线程</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">info</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> threads</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">...</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">* 1    Thread 0x7fce6e201740 (</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">LWP</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2314</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"python"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 0x00007fce6db070e3 in </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">epoll_wait</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ()</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    at</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ../sysdeps/unix/syscall-template.S:81</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><img src="@source/unix/Linux/Troubleshooting/img/info-thrads.jpg"> 
<p>请注意 <strong>*号</strong> 哦——它标识的是当前线程</p>
<p>切换线程，如切换到 <strong>2</strong> 号线程（<em>将其设置为当前线程进行调试</em> ）</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">thread</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><img src="@source/unix/Linux/Troubleshooting/img/select-thread.jpg"> 
<p>查看当前线程的相关信息，则使用 <code v-pre>py-list</code> ，可以清楚看到当前执行到代码的第几行， 还有前后若干行的代码可以对照</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">gdb</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">py-list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2025</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">         # Open external files with our Mac app</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2026</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">         if</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sys.platform</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ==</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "darwin"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'Spyder.app'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> __file__:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2027</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             main.connect</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">app,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> SIGNAL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">'open_external_file(QString)'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">,</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2028</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                          lambda</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> fname:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> main.open_external_file</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">fname</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2029</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>2030        </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">app.exec_</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2031</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">         return</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> main</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2032</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2033</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2034</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     def</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> __remove_temp_session</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2035</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">         if</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> osp.isfile</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">TEMP_SESSION_PATH</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">:</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>查看所有进程执行位置</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span>(gdb) thread apply all py-list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>命令如下：</p>
<ul>
<li>
<p><code v-pre>py-bt :</code> 输出 <strong>python</strong> 应用程序调用堆栈</p>
</li>
<li>
<p><code v-pre>py-bt-full :</code> 查看当前 <strong>python</strong> 应用程序调用堆栈，并且显示每个 <strong>frame</strong> 的详细情况</p>
</li>
<li>
<p><code v-pre>py-list:</code>  显示代码查看当前 <strong>python</strong> 应用程序上下文</p>
</li>
<li>
<p><code v-pre>py-print:</code> 查看 <strong>python</strong> 变量</p>
</li>
<li>
<p><code v-pre>py-locals:</code> 查看 <strong>locals</strong> 变量</p>
</li>
<li>
<p><code v-pre>py-up:</code> 调用栈 <strong>frame</strong> 向上一级</p>
</li>
<li>
<p><code v-pre>py-down:</code> 调用栈向下一级</p>
</li>
</ul>
</div></template>


