export const data = JSON.parse("{\"key\":\"v-67ba2084\",\"path\":\"/tool/Docker/docker%E5%AE%B9%E5%99%A8.html\",\"title\":\"Docker 安装\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Docker 安装\",\"date\":\"2022-07-03T00:00:00.000Z\",\"category\":[\"运维\",\"Docker\"],\"tag\":[\"Docker\",\"工具\"],\"star\":true,\"summary\":\"Docker 的基础概念和安装说明\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/tool/Docker/docker%E5%AE%B9%E5%99%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚 ▪ 寄\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Docker 安装\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://igarashi-g.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Docker 安装\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Docker\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-03T00:00:00.000Z\"}]]},\"excerpt\":\"<p><strong>Docker</strong> 的基础概念和安装说明</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. Docker概述\",\"slug\":\"_1-docker概述\",\"link\":\"#_1-docker概述\",\"children\":[{\"level\":3,\"title\":\"1.1 教程\",\"slug\":\"_1-1-教程\",\"link\":\"#_1-1-教程\",\"children\":[]},{\"level\":3,\"title\":\"1.2 Linux 容器\",\"slug\":\"_1-2-linux-容器\",\"link\":\"#_1-2-linux-容器\",\"children\":[]},{\"level\":3,\"title\":\"1.3 容器与虚拟机对比\",\"slug\":\"_1-3-容器与虚拟机对比\",\"link\":\"#_1-3-容器与虚拟机对比\",\"children\":[]},{\"level\":3,\"title\":\"1.4 Docker 架构\",\"slug\":\"_1-4-docker-架构\",\"link\":\"#_1-4-docker-架构\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 安装\",\"slug\":\"_2-安装\",\"link\":\"#_2-安装\",\"children\":[{\"level\":3,\"title\":\"2.1 CentOS\",\"slug\":\"_2-1-centos\",\"link\":\"#_2-1-centos\",\"children\":[]},{\"level\":3,\"title\":\"2.2 Debian\",\"slug\":\"_2-2-debian\",\"link\":\"#_2-2-debian\",\"children\":[]},{\"level\":3,\"title\":\"2.3 Windows\",\"slug\":\"_2-3-windows\",\"link\":\"#_2-3-windows\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 实现原理\",\"slug\":\"_3-实现原理\",\"link\":\"#_3-实现原理\",\"children\":[{\"level\":3,\"title\":\"3.1 Namespace 资源隔离\",\"slug\":\"_3-1-namespace-资源隔离\",\"link\":\"#_3-1-namespace-资源隔离\",\"children\":[]},{\"level\":3,\"title\":\"3.2 CGroup 资源限制\",\"slug\":\"_3-2-cgroup-资源限制\",\"link\":\"#_3-2-cgroup-资源限制\",\"children\":[]},{\"level\":3,\"title\":\"3.3 UnionFS 联合文件系统\",\"slug\":\"_3-3-unionfs-联合文件系统\",\"link\":\"#_3-3-unionfs-联合文件系统\",\"children\":[]}]}],\"readingTime\":{\"minutes\":10.71,\"words\":3213},\"filePathRelative\":\"tool/Docker/docker容器.md\",\"localizedDate\":\"2022年7月3日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
