export const data = JSON.parse("{\"key\":\"v-e87a30d8\",\"path\":\"/tool/Kubernets/k8s%E5%AE%89%E8%A3%85.html\",\"title\":\"Kubernets 安装(单Master)\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Kubernets 安装(单Master)\",\"date\":\"2022-09-27T00:00:00.000Z\",\"category\":[\"运维\",\"k8s\"],\"tag\":[\"k8s\"],\"star\":true,\"summary\":\"记录安装 Docker 版（老版本）的 k8s 单 Master 集群\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/igarashi-blog/igarashi-blog/tool/Kubernets/k8s%E5%AE%89%E8%A3%85.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Kubernets 安装(单Master)\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"k8s\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-09-27T00:00:00.000Z\"}]]},\"excerpt\":\"<p>记录安装 <strong>Docker</strong> 版（老版本）的 <strong>k8s</strong> 单 <strong>Master</strong> 集群</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. 准备工作\",\"slug\":\"_1-准备工作\",\"link\":\"#_1-准备工作\",\"children\":[]},{\"level\":2,\"title\":\"2. 初始化配置\",\"slug\":\"_2-初始化配置\",\"link\":\"#_2-初始化配置\",\"children\":[]},{\"level\":2,\"title\":\"3. 安装基础软件包\",\"slug\":\"_3-安装基础软件包\",\"link\":\"#_3-安装基础软件包\",\"children\":[{\"level\":3,\"title\":\"3.1 安装docker\",\"slug\":\"_3-1-安装docker\",\"link\":\"#_3-1-安装docker\",\"children\":[]},{\"level\":3,\"title\":\"3.2 安装kubeadm，kubelet 和 kubectl\",\"slug\":\"_3-2-安装kubeadm-kubelet-和-kubectl\",\"link\":\"#_3-2-安装kubeadm-kubelet-和-kubectl\",\"children\":[]}]},{\"level\":2,\"title\":\"4. 初始化集群\",\"slug\":\"_4-初始化集群\",\"link\":\"#_4-初始化集群\",\"children\":[]},{\"level\":2,\"title\":\"5. 安装网络插件\",\"slug\":\"_5-安装网络插件\",\"link\":\"#_5-安装网络插件\",\"children\":[{\"level\":3,\"title\":\"5.1 网络插件 flannel\",\"slug\":\"_5-1-网络插件-flannel\",\"link\":\"#_5-1-网络插件-flannel\",\"children\":[]},{\"level\":3,\"title\":\"5.2 网络插件 calico\",\"slug\":\"_5-2-网络插件-calico\",\"link\":\"#_5-2-网络插件-calico\",\"children\":[]},{\"level\":3,\"title\":\"5.3 创建测试 Nginx 服务\",\"slug\":\"_5-3-创建测试-nginx-服务\",\"link\":\"#_5-3-创建测试-nginx-服务\",\"children\":[]},{\"level\":3,\"title\":\"5.4 设置master节点是否可调度（可选）\",\"slug\":\"_5-4-设置master节点是否可调度-可选\",\"link\":\"#_5-4-设置master节点是否可调度-可选\",\"children\":[]}]},{\"level\":2,\"title\":\"6. 安装Dashboard\",\"slug\":\"_6-安装dashboard\",\"link\":\"#_6-安装dashboard\",\"children\":[]}],\"readingTime\":{\"minutes\":11.57,\"words\":3470},\"filePathRelative\":\"tool/Kubernets/k8s安装.md\",\"localizedDate\":\"2022年9月27日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
