export const data = JSON.parse("{\"key\":\"v-6abcb6a6\",\"path\":\"/python/%E8%AF%AD%E8%A8%80/%E8%BF%9B%E9%98%B6/.~%E5%87%BD%E6%95%B0.html\",\"title\":\"函数\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"函数\",\"date\":\"2020-06-06T00:00:00.000Z\",\"category\":[\"Python\"],\"tag\":[\"Python\",\"函数\"],\"star\":true,\"summary\":\"把函数视为 一等对象\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/igarashi-blog/python/%E8%AF%AD%E8%A8%80/%E8%BF%9B%E9%98%B6/.~%E5%87%BD%E6%95%B0.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"是五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"函数\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Python\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"函数\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-06-06T00:00:00.000Z\"}]]},\"excerpt\":\"<p>把函数视为 <strong>一等对象</strong></p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. 概念\",\"slug\":\"_1-概念\",\"link\":\"#_1-概念\",\"children\":[{\"level\":3,\"title\":\"1.1 函数定义\",\"slug\":\"_1-1-函数定义\",\"link\":\"#_1-1-函数定义\",\"children\":[]},{\"level\":3,\"title\":\"1.2 函数地址\",\"slug\":\"_1-2-函数地址\",\"link\":\"#_1-2-函数地址\",\"children\":[]},{\"level\":3,\"title\":\"1.3 函数的作用\",\"slug\":\"_1-3-函数的作用\",\"link\":\"#_1-3-函数的作用\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 函数参数\",\"slug\":\"_2-函数参数\",\"link\":\"#_2-函数参数\",\"children\":[{\"level\":3,\"title\":\"2.1 参数类别\",\"slug\":\"_2-1-参数类别\",\"link\":\"#_2-1-参数类别\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 函数返回值(return)\",\"slug\":\"_3-函数返回值-return\",\"link\":\"#_3-函数返回值-return\",\"children\":[]},{\"level\":2,\"title\":\"4. 函数的作用域\",\"slug\":\"_4-函数的作用域\",\"link\":\"#_4-函数的作用域\",\"children\":[{\"level\":3,\"title\":\"4.1 作用域 LEGB\",\"slug\":\"_4-1-作用域-legb\",\"link\":\"#_4-1-作用域-legb\",\"children\":[]},{\"level\":3,\"title\":\"4.2 全局变量和局部变量\",\"slug\":\"_4-2-全局变量和局部变量\",\"link\":\"#_4-2-全局变量和局部变量\",\"children\":[]},{\"level\":3,\"title\":\"4.3 命名空间\",\"slug\":\"_4-3-命名空间\",\"link\":\"#_4-3-命名空间\",\"children\":[]}]},{\"level\":2,\"title\":\"5. 进阶\",\"slug\":\"_5-进阶\",\"link\":\"#_5-进阶\",\"children\":[{\"level\":3,\"title\":\"5.1 函数为参\",\"slug\":\"_5-1-函数为参\",\"link\":\"#_5-1-函数为参\",\"children\":[]},{\"level\":3,\"title\":\"5.2 嵌套\",\"slug\":\"_5-2-嵌套\",\"link\":\"#_5-2-嵌套\",\"children\":[]},{\"level\":3,\"title\":\"5.3 递归\",\"slug\":\"_5-3-递归\",\"link\":\"#_5-3-递归\",\"children\":[]},{\"level\":3,\"title\":\"5.4 常用内置函数\",\"slug\":\"_5-4-常用内置函数\",\"link\":\"#_5-4-常用内置函数\",\"children\":[]},{\"level\":3,\"title\":\"5.5 题外话\",\"slug\":\"_5-5-题外话\",\"link\":\"#_5-5-题外话\",\"children\":[]}]}],\"readingTime\":{\"minutes\":11,\"words\":3301},\"filePathRelative\":\"python/语言/进阶/.~函数.md\",\"localizedDate\":\"2020年6月6日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
