export const data = JSON.parse("{\"key\":\"v-fabf775c\",\"path\":\"/tool/Python%E9%A1%B9%E7%9B%AE%E6%89%93%E5%8C%85/python%E6%89%93rpm.html\",\"title\":\"Python项目打RPM包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Python项目打RPM包\",\"order\":1,\"group\":{\"title\":\"打包\",\"order\":21},\"summary\":\"python 打 rpm 包 1. 环境 rpm 从 4.5x 以上的版本将 rpmbuild 默认工作路径移动到 /root/rpmbuild 目录 推荐打包时尽量不用 root 账户操作（防止执行些不可挽回的命令） 环境：\\rCentOS Linux release 7.5.1804 (Core); \\rRPM version 4.11.3; 如果想发布 r\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/igarashi-blog/igarashi-blog/tool/Python%E9%A1%B9%E7%9B%AE%E6%89%93%E5%8C%85/python%E6%89%93rpm.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Python项目打RPM包\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1. 环境\",\"slug\":\"_1-环境\",\"link\":\"#_1-环境\",\"children\":[{\"level\":3,\"title\":\"1.1 安装工具\",\"slug\":\"_1-1-安装工具\",\"link\":\"#_1-1-安装工具\",\"children\":[]},{\"level\":3,\"title\":\"1.2 建立环境\",\"slug\":\"_1-2-建立环境\",\"link\":\"#_1-2-建立环境\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 打包入门\",\"slug\":\"_2-打包入门\",\"link\":\"#_2-打包入门\",\"children\":[{\"level\":3,\"title\":\"2.1 SPEC 阶段与目录的对应关系\",\"slug\":\"_2-1-spec-阶段与目录的对应关系\",\"link\":\"#_2-1-spec-阶段与目录的对应关系\",\"children\":[]},{\"level\":3,\"title\":\"2.2 工具使用\",\"slug\":\"_2-2-工具使用\",\"link\":\"#_2-2-工具使用\",\"children\":[]},{\"level\":3,\"title\":\"2.3 生成 SPEC 文件\",\"slug\":\"_2-3-生成-spec-文件\",\"link\":\"#_2-3-生成-spec-文件\",\"children\":[]},{\"level\":3,\"title\":\"2.4 示例文件：\",\"slug\":\"_2-4-示例文件\",\"link\":\"#_2-4-示例文件\",\"children\":[]},{\"level\":3,\"title\":\"2.5 打包命令 rpmbuild\",\"slug\":\"_2-5-打包命令-rpmbuild\",\"link\":\"#_2-5-打包命令-rpmbuild\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 准备用来打包的软件\",\"slug\":\"_3-准备用来打包的软件\",\"link\":\"#_3-准备用来打包的软件\",\"children\":[{\"level\":3,\"title\":\"3.1 准备打包的源代码\",\"slug\":\"_3-1-准备打包的源代码\",\"link\":\"#_3-1-准备打包的源代码\",\"children\":[]}]},{\"level\":2,\"title\":\"4. 打包软件\",\"slug\":\"_4-打包软件\",\"link\":\"#_4-打包软件\",\"children\":[{\"level\":3,\"title\":\"4.1 什么是 RPM\",\"slug\":\"_4-1-什么是-rpm\",\"link\":\"#_4-1-什么是-rpm\",\"children\":[]},{\"level\":3,\"title\":\"4.2 RPM 类型\",\"slug\":\"_4-2-rpm-类型\",\"link\":\"#_4-2-rpm-类型\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.18,\"words\":1554},\"filePathRelative\":\"tool/Python项目打包/python打rpm.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
