export const data = JSON.parse("{\"key\":\"v-335ff002\",\"path\":\"/python/Framework/FastAPI/FastAPI%E5%9F%BA%E7%A1%80.html\",\"title\":\"FastAPI基础\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"FastAPI基础\",\"order\":1,\"group\":{\"title\":\"FastAPI\",\"order\":24},\"summary\":\"FastAPI FastAPI 文档| GitHub FastAPI 简介 1.特性：\\r快速：理论上媲美 nodeJS 和 GO; \\r快速编码：效率提升 2~3 倍; \\r更少错误：理论减少 40%; \\r直观、简易、短、健壮; \\r基于标准：完全兼容 API 的开放标准 openAPI & JSON Schema; 2.层次结构 FastAPI 是基于 Star\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/igarashi-blog/python/Framework/FastAPI/FastAPI%E5%9F%BA%E7%A1%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"是五十岚吖\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"FastAPI基础\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"FastAPI 简介\",\"slug\":\"fastapi-简介\",\"link\":\"#fastapi-简介\",\"children\":[{\"level\":3,\"title\":\"1.特性：\",\"slug\":\"_1-特性\",\"link\":\"#_1-特性\",\"children\":[]},{\"level\":3,\"title\":\"2.层次结构\",\"slug\":\"_2-层次结构\",\"link\":\"#_2-层次结构\",\"children\":[]},{\"level\":3,\"title\":\"3.可选依赖\",\"slug\":\"_3-可选依赖\",\"link\":\"#_3-可选依赖\",\"children\":[]}]},{\"level\":2,\"title\":\"一、Request 请求相关部分\",\"slug\":\"一、request-请求相关部分\",\"link\":\"#一、request-请求相关部分\",\"children\":[{\"level\":3,\"title\":\"1.url 和 参数获取\",\"slug\":\"_1-url-和-参数获取\",\"link\":\"#_1-url-和-参数获取\",\"children\":[]},{\"level\":3,\"title\":\"2.Pydantic & FastAPI 的 各种参数数据验证及数据模型\",\"slug\":\"_2-pydantic-fastapi-的-各种参数数据验证及数据模型\",\"link\":\"#_2-pydantic-fastapi-的-各种参数数据验证及数据模型\",\"children\":[]},{\"level\":3,\"title\":\"（6）嵌套数据模型：\",\"slug\":\"_6-嵌套数据模型\",\"link\":\"#_6-嵌套数据模型\",\"children\":[]},{\"level\":3,\"title\":\"（7） 额外的数据校验类型\",\"slug\":\"_7-额外的数据校验类型\",\"link\":\"#_7-额外的数据校验类型\",\"children\":[]},{\"level\":3,\"title\":\"（8）Cookie 校验类型\",\"slug\":\"_8-cookie-校验类型\",\"link\":\"#_8-cookie-校验类型\",\"children\":[]},{\"level\":3,\"title\":\"（9）Header 校验类型\",\"slug\":\"_9-header-校验类型\",\"link\":\"#_9-header-校验类型\",\"children\":[]}]},{\"level\":2,\"title\":\"二、Response 响应相关部分\",\"slug\":\"二、response-响应相关部分\",\"link\":\"#二、response-响应相关部分\",\"children\":[{\"level\":3,\"title\":\"1.响应模型：\",\"slug\":\"_1-响应模型\",\"link\":\"#_1-响应模型\",\"children\":[]}]},{\"level\":2,\"title\":\"FastAPi 相关配置\",\"slug\":\"fastapi-相关配置\",\"link\":\"#fastapi-相关配置\",\"children\":[{\"level\":3,\"title\":\"1.静态文件的路径导入：\",\"slug\":\"_1-静态文件的路径导入\",\"link\":\"#_1-静态文件的路径导入\",\"children\":[]},{\"level\":3,\"title\":\"2.fastapi 启用热更新：\",\"slug\":\"_2-fastapi-启用热更新\",\"link\":\"#_2-fastapi-启用热更新\",\"children\":[]}]}],\"readingTime\":{\"minutes\":18.21,\"words\":5464},\"filePathRelative\":\"python/Framework/FastAPI/FastAPI基础.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
