export const data = JSON.parse("{\"key\":\"v-fde169d0\",\"path\":\"/python/%E7%94%9F%E6%80%81/%E5%BC%82%E6%AD%A5%E4%BB%BB%E5%8A%A1/Celery%E5%9F%BA%E7%A1%80.html\",\"title\":\"Celery基础\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Celery基础\",\"order\":2,\"summary\":\"Celery Task Celery 是一个简单、灵活且可靠的，处理大量消息的分布式系统，\\r专注于实时处理的异步任务队列; \\r支持任务调度等定时任务; 一、celery 概述： 1.celery 组成： Celery 的架构由三部分组成，消息中间件（message broker），任务执行单元（worker）和任务执行结果存储（task result sto\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/igarashi-blog/igarashi-blog/python/%E7%94%9F%E6%80%81/%E5%BC%82%E6%AD%A5%E4%BB%BB%E5%8A%A1/Celery%E5%9F%BA%E7%A1%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Celery基础\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"一、celery 概述：\",\"slug\":\"一、celery-概述\",\"link\":\"#一、celery-概述\",\"children\":[{\"level\":3,\"title\":\"1.celery 组成：\",\"slug\":\"_1-celery-组成\",\"link\":\"#_1-celery-组成\",\"children\":[]},{\"level\":3,\"title\":\"2.使用场景：\",\"slug\":\"_2-使用场景\",\"link\":\"#_2-使用场景\",\"children\":[]},{\"level\":3,\"title\":\"3. 安装：\",\"slug\":\"_3-安装\",\"link\":\"#_3-安装\",\"children\":[]},{\"level\":3,\"title\":\"4.执行流程：\",\"slug\":\"_4-执行流程\",\"link\":\"#_4-执行流程\",\"children\":[]}]},{\"level\":2,\"title\":\"二、celery 创建任务：\",\"slug\":\"二、celery-创建任务\",\"link\":\"#二、celery-创建任务\",\"children\":[{\"level\":3,\"title\":\"1.创建简单任务\",\"slug\":\"_1-创建简单任务\",\"link\":\"#_1-创建简单任务\",\"children\":[]},{\"level\":3,\"title\":\"2. 通过引入单独配置文件，创建任务\",\"slug\":\"_2-通过引入单独配置文件-创建任务\",\"link\":\"#_2-通过引入单独配置文件-创建任务\",\"children\":[]}]},{\"level\":2,\"title\":\"三、celery 启动任务\",\"slug\":\"三、celery-启动任务\",\"link\":\"#三、celery-启动任务\",\"children\":[{\"level\":3,\"title\":\"1. 直接终端执行命令：\",\"slug\":\"_1-直接终端执行命令\",\"link\":\"#_1-直接终端执行命令\",\"children\":[]},{\"level\":3,\"title\":\"2.写脚本执行：\",\"slug\":\"_2-写脚本执行\",\"link\":\"#_2-写脚本执行\",\"children\":[]}]},{\"level\":2,\"title\":\"四、创建 celery 生产者\",\"slug\":\"四、创建-celery-生产者\",\"link\":\"#四、创建-celery-生产者\",\"children\":[]},{\"level\":2,\"title\":\"五、获取任务执行结果\",\"slug\":\"五、获取任务执行结果\",\"link\":\"#五、获取任务执行结果\",\"children\":[{\"level\":3,\"title\":\"1.通过 AsyncResult 进行简单判断：\",\"slug\":\"_1-通过-asyncresult-进行简单判断\",\"link\":\"#_1-通过-asyncresult-进行简单判断\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.33,\"words\":1000},\"filePathRelative\":\"python/生态/异步任务/Celery基础.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
