<template><div><p><a href="https://github.com/rdesktop" target="_blank" rel="noopener noreferrer">rdesktop</a> 是微软 <strong>RDP</strong> 协议的开源客户端</p>
<!-- more -->
<h1 id="rdesktop远程工具" tabindex="-1"><a class="header-anchor" href="#rdesktop远程工具"><span>rdesktop远程工具</span></a></h1>
<h3 id="_1-安装" tabindex="-1"><a class="header-anchor" href="#_1-安装"><span>1. 安装</span></a></h3>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">apt-get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> rdesktop</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-使用命令" tabindex="-1"><a class="header-anchor" href="#_2-使用命令"><span>2. 使用命令</span></a></h3>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-d:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 域</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-s:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> shell命令</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (登录运行命令之后就退出)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-c:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 工作目录（应该是-s的子命令），-s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> shell命令的一个参数</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-p:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> password</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (- </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prompt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-n:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 客户端（本地）主机名，默认为本地主机名</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-k:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 服务器上的键盘布局选择</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (en-us, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">de,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sv,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> etc.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-g:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 桌面分辨率（宽x高）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-i:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> enables</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> smartcard</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> authentication,</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> password</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> used</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> as</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pin</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 全屏模式（Ctrl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Alt</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Enter</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 退出全屏模式）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-b:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 强制位图刷新（没发现什么用）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-L:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 本地编码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-A:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 无缝虚拟应用程序到本地</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-B:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> use</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> BackingStore</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> X-server</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (if </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">available</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-e:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> encryption</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (French </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">TS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) 禁用加密</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-E:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> encryption</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> client</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 从客户端到服务器，禁用加密。</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-m:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 不允许拖动（不传递鼠标的拖动事件）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-C:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> use</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> private</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> colour</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> map</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-D:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 不显示窗口标题栏（只有远程桌面窗口，没有关闭和最小化按钮）</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-K:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 窗口切换快捷热键（Alt+Tab）不传递到远程桌面</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-S:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 标题按钮的大小，个人觉得这个参数很无用，或者我还没弄明白到底什么意思。</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-T:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 窗口标题</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-t:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> use</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ctrl</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-N:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 数字键盘同步</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-X:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 给定另一个窗口的标识，嵌入到另一个窗口</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-a:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> connection</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> colour</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> depth</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 选择颜色深度</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-z:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 启用rdp压缩</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-x:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> RDP5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> experience</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (m[odem </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">28.8],</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> b[roadband],</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> l[an]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> hex</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> nr.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-P:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 持久位图缓存</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-r:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 设备重定向（参数可以重复使用）</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>
<p>示例：</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 尽可能快速输出的将剪贴板和声音映射过去</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">rdesktop</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -P</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -r</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> clipboard:PROMARYCLIPBOARD</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -r</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sound:local</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 192.168.3.75</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ul>
<h3 id="_3-问题" tabindex="-1"><a class="header-anchor" href="#_3-问题"><span>3. 问题</span></a></h3>
<ul>
<li>
<p>解决声音失效的办法</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 要找出哪些进程正在访问声音设备</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">lsof</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /dev/snd/</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">*</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 干掉它</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">fuser</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /dev/snd/</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">*</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ul>
</div></template>


