export const data = JSON.parse("{\"key\":\"v-3af96590\",\"path\":\"/python/%E8%AF%AD%E8%A8%80/%E5%9F%BA%E7%A1%80/python%E6%89%93rpm.html\",\"title\":\"Python项目打包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Python项目打包\",\"date\":\"2021-09-17T00:00:00.000Z\",\"category\":[\"Python\",\"打包\"],\"tag\":[\"打包\"],\"summary\":\"Python 打包 rpm or wheel\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/python/%E8%AF%AD%E8%A8%80/%E5%9F%BA%E7%A1%80/python%E6%89%93rpm.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚 ▪ 寄\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Python项目打包\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"打包\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-09-17T00:00:00.000Z\"}]]},\"excerpt\":\"<p><strong>Python</strong> 打包 <strong>rpm</strong> <strong>or</strong> <strong>wheel</strong></p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. python 打 rpm 包\",\"slug\":\"_1-python-打-rpm-包\",\"link\":\"#_1-python-打-rpm-包\",\"children\":[{\"level\":3,\"title\":\"1.1 安装工具\",\"slug\":\"_1-1-安装工具\",\"link\":\"#_1-1-安装工具\",\"children\":[]},{\"level\":3,\"title\":\"1.2 建立环境\",\"slug\":\"_1-2-建立环境\",\"link\":\"#_1-2-建立环境\",\"children\":[]},{\"level\":3,\"title\":\"1.3 SPEC 阶段与目录的对应关系\",\"slug\":\"_1-3-spec-阶段与目录的对应关系\",\"link\":\"#_1-3-spec-阶段与目录的对应关系\",\"children\":[]},{\"level\":3,\"title\":\"1.4 工具使用\",\"slug\":\"_1-4-工具使用\",\"link\":\"#_1-4-工具使用\",\"children\":[]},{\"level\":3,\"title\":\"1.5 生成 SPEC 文件\",\"slug\":\"_1-5-生成-spec-文件\",\"link\":\"#_1-5-生成-spec-文件\",\"children\":[]},{\"level\":3,\"title\":\"1.6 示例文件：\",\"slug\":\"_1-6-示例文件\",\"link\":\"#_1-6-示例文件\",\"children\":[]},{\"level\":3,\"title\":\"1.7 打包命令 rpmbuild\",\"slug\":\"_1-7-打包命令-rpmbuild\",\"link\":\"#_1-7-打包命令-rpmbuild\",\"children\":[]},{\"level\":3,\"title\":\"1.8 准备打包的源代码\",\"slug\":\"_1-8-准备打包的源代码\",\"link\":\"#_1-8-准备打包的源代码\",\"children\":[]}]},{\"level\":2,\"title\":\"2. python 项目打包 wheel\",\"slug\":\"_2-python-项目打包-wheel\",\"link\":\"#_2-python-项目打包-wheel\",\"children\":[{\"level\":3,\"title\":\"2.1 编写 setup.py 文件\",\"slug\":\"_2-1-编写-setup-py-文件\",\"link\":\"#_2-1-编写-setup-py-文件\",\"children\":[]},{\"level\":3,\"title\":\"2.2 编写 .service 文件\",\"slug\":\"_2-2-编写-service-文件\",\"link\":\"#_2-2-编写-service-文件\",\"children\":[]},{\"level\":3,\"title\":\"2.3 去掉依赖\",\"slug\":\"_2-3-去掉依赖\",\"link\":\"#_2-3-去掉依赖\",\"children\":[]}]},{\"level\":2,\"title\":\"2.4 打包到镜像\",\"slug\":\"_2-4-打包到镜像\",\"link\":\"#_2-4-打包到镜像\",\"children\":[]}],\"readingTime\":{\"minutes\":9.76,\"words\":2929},\"filePathRelative\":\"python/语言/基础/python打rpm.md\",\"localizedDate\":\"2021年9月17日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
