export const data = JSON.parse("{\"key\":\"v-57f16400\",\"path\":\"/python/%E8%AF%AD%E8%A8%80/%E5%9F%BA%E7%A1%80/python%E6%89%93%E5%8C%85.html\",\"title\":\"Python项目打RPM包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Python项目打RPM包\",\"order\":1,\"group\":{\"title\":\"打包\",\"order\":21},\"summary\":\"python 打 rpm 包 1. 环境 rpm 从 4.5x 以上的版本将 rpmbuild 默认工作路径移动到 /root/rpmbuild 目录 推荐打包时尽量不用 root 账户操作（防止执行些不可挽回的命令） 环境：\\rCentOS Linux release 7.5.1804 (Core); \\rRPM version 4.11.3; 如果想发布 r\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/python/%E8%AF%AD%E8%A8%80/%E5%9F%BA%E7%A1%80/python%E6%89%93%E5%8C%85.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚 ▪ 寄\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Python项目打RPM包\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1. 环境\",\"slug\":\"_1-环境\",\"link\":\"#_1-环境\",\"children\":[{\"level\":3,\"title\":\"1.1 安装工具\",\"slug\":\"_1-1-安装工具\",\"link\":\"#_1-1-安装工具\",\"children\":[]},{\"level\":3,\"title\":\"1.2 建立环境\",\"slug\":\"_1-2-建立环境\",\"link\":\"#_1-2-建立环境\",\"children\":[]}]},{\"level\":2,\"title\":\"2. 打包入门\",\"slug\":\"_2-打包入门\",\"link\":\"#_2-打包入门\",\"children\":[{\"level\":3,\"title\":\"2.1 SPEC 阶段与目录的对应关系\",\"slug\":\"_2-1-spec-阶段与目录的对应关系\",\"link\":\"#_2-1-spec-阶段与目录的对应关系\",\"children\":[]},{\"level\":3,\"title\":\"2.2 工具使用\",\"slug\":\"_2-2-工具使用\",\"link\":\"#_2-2-工具使用\",\"children\":[]},{\"level\":3,\"title\":\"2.3 生成 SPEC 文件\",\"slug\":\"_2-3-生成-spec-文件\",\"link\":\"#_2-3-生成-spec-文件\",\"children\":[]},{\"level\":3,\"title\":\"2.4 示例文件：\",\"slug\":\"_2-4-示例文件\",\"link\":\"#_2-4-示例文件\",\"children\":[]},{\"level\":3,\"title\":\"2.5 打包命令 rpmbuild\",\"slug\":\"_2-5-打包命令-rpmbuild\",\"link\":\"#_2-5-打包命令-rpmbuild\",\"children\":[]}]},{\"level\":2,\"title\":\"3. 准备用来打包的软件\",\"slug\":\"_3-准备用来打包的软件\",\"link\":\"#_3-准备用来打包的软件\",\"children\":[{\"level\":3,\"title\":\"3.1 准备打包的源代码\",\"slug\":\"_3-1-准备打包的源代码\",\"link\":\"#_3-1-准备打包的源代码\",\"children\":[]}]},{\"level\":2,\"title\":\"4. 打包软件\",\"slug\":\"_4-打包软件\",\"link\":\"#_4-打包软件\",\"children\":[{\"level\":3,\"title\":\"4.1 什么是 RPM\",\"slug\":\"_4-1-什么是-rpm\",\"link\":\"#_4-1-什么是-rpm\",\"children\":[]},{\"level\":3,\"title\":\"4.2 RPM 类型\",\"slug\":\"_4-2-rpm-类型\",\"link\":\"#_4-2-rpm-类型\",\"children\":[]}]},{\"level\":2,\"title\":\"1.编写 setup.py 文件\",\"slug\":\"_1-编写-setup-py-文件\",\"link\":\"#_1-编写-setup-py-文件\",\"children\":[]},{\"level\":2,\"title\":\"2. 编写 .service 文件\",\"slug\":\"_2-编写-service-文件\",\"link\":\"#_2-编写-service-文件\",\"children\":[]},{\"level\":2,\"title\":\"3. 去掉依赖\",\"slug\":\"_3-去掉依赖\",\"link\":\"#_3-去掉依赖\",\"children\":[]},{\"level\":2,\"title\":\"4. 打包到镜像\",\"slug\":\"_4-打包到镜像\",\"link\":\"#_4-打包到镜像\",\"children\":[]}],\"readingTime\":{\"minutes\":9.79,\"words\":2937},\"filePathRelative\":\"python/语言/基础/python打包.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
