export const data = JSON.parse("{\"key\":\"v-29b93e8a\",\"path\":\"/python/%E5%BA%93/%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E6%BA%90%E5%8C%85/Psutil.html\",\"title\":\"psutil\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"psutil\",\"order\":2,\"summary\":\"psutil 日常处理运维相关，psutil = process and system utilities 不仅可以通过一两行代码实现系统监控，还可以跨平台使用 https://psutil.readthedocs.io/ 安装 psutil pip install psutil import psutil 一、CPU 相关： 1. 获取 CPU 信息： C\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/igarashi-blog/python/%E5%BA%93/%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E6%BA%90%E5%8C%85/Psutil.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"是五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"psutil\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"安装 psutil\",\"slug\":\"安装-psutil\",\"link\":\"#安装-psutil\",\"children\":[]},{\"level\":2,\"title\":\"一、CPU 相关：\",\"slug\":\"一、cpu-相关\",\"link\":\"#一、cpu-相关\",\"children\":[{\"level\":3,\"title\":\"1. 获取 CPU 信息：\",\"slug\":\"_1-获取-cpu-信息\",\"link\":\"#_1-获取-cpu-信息\",\"children\":[]}]},{\"level\":2,\"title\":\"二、内存相关：\",\"slug\":\"二、内存相关\",\"link\":\"#二、内存相关\",\"children\":[{\"level\":3,\"title\":\"1.获取内存信息：\",\"slug\":\"_1-获取内存信息\",\"link\":\"#_1-获取内存信息\",\"children\":[]}]},{\"level\":2,\"title\":\"三、磁盘相关：\",\"slug\":\"三、磁盘相关\",\"link\":\"#三、磁盘相关\",\"children\":[{\"level\":3,\"title\":\"1.获取磁盘信息\",\"slug\":\"_1-获取磁盘信息\",\"link\":\"#_1-获取磁盘信息\",\"children\":[]}]},{\"level\":2,\"title\":\"四、网络相关：\",\"slug\":\"四、网络相关\",\"link\":\"#四、网络相关\",\"children\":[{\"level\":3,\"title\":\"1.获取网络信息\",\"slug\":\"_1-获取网络信息\",\"link\":\"#_1-获取网络信息\",\"children\":[]}]},{\"level\":2,\"title\":\"五、进程相关：\",\"slug\":\"五、进程相关\",\"link\":\"#五、进程相关\",\"children\":[{\"level\":3,\"title\":\"1.获取进程信息\",\"slug\":\"_1-获取进程信息\",\"link\":\"#_1-获取进程信息\",\"children\":[]}]},{\"level\":2,\"title\":\"六、使用 Popen 类：\",\"slug\":\"六、使用-popen-类\",\"link\":\"#六、使用-popen-类\",\"children\":[{\"level\":3,\"title\":\"popen 类可以获取用户启动的应用程序进程信息。\",\"slug\":\"popen-类可以获取用户启动的应用程序进程信息。\",\"link\":\"#popen-类可以获取用户启动的应用程序进程信息。\",\"children\":[]}]},{\"level\":2,\"title\":\"、测试\",\"slug\":\"、测试\",\"link\":\"#、测试\",\"children\":[{\"level\":3,\"title\":\"1. test()函数\",\"slug\":\"_1-test-函数\",\"link\":\"#_1-test-函数\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.21,\"words\":663},\"filePathRelative\":\"python/库/第三方开源包/Psutil.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
