<template><div><p><strong>UFS</strong> 管理平台 通过<strong>ldap3</strong> 对接 <strong>AD</strong> 域，加入域、退出域、<strong>CIFS</strong> 权限认证等</p>
<!-- more -->
<h1 id="python-对接ad域" tabindex="-1"><a class="header-anchor" href="#python-对接ad域" aria-hidden="true">#</a> Python 对接AD域</h1>
<h2 id="_1-需求" tabindex="-1"><a class="header-anchor" href="#_1-需求" aria-hidden="true">#</a> 1. 需求</h2>
<h2 id="_2-ldap3" tabindex="-1"><a class="header-anchor" href="#_2-ldap3" aria-hidden="true">#</a> 2. ldap3</h2>
<p><strong>pip</strong> 安装 <a href="https://ldap3.readthedocs.io/en/latest/welcome.html" target="_blank" rel="noopener noreferrer">ldap3<ExternalLinkIcon/></a> 库</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ pip Install ldap3
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>简单建立同步连接</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">from</span> ldap3 <span class="token keyword">import</span> Server<span class="token punctuation">,</span> Connection<span class="token punctuation">,</span> ALL

server <span class="token operator">=</span> Server<span class="token punctuation">(</span><span class="token string">"uit.devops.local"</span><span class="token punctuation">,</span> get_info<span class="token operator">=</span>ALL<span class="token punctuation">)</span>	<span class="token comment"># Windows 搭建的AD Server 域名</span>
conn <span class="token operator">=</span> Connection<span class="token punctuation">(</span>server<span class="token punctuation">,</span> auto_bind<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span>

<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">repr</span><span class="token punctuation">(</span>server<span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">repr</span><span class="token punctuation">(</span>server<span class="token punctuation">.</span>info<span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">repr</span><span class="token punctuation">(</span>conn<span class="token punctuation">)</span><span class="token punctuation">)</span>

ret <span class="token operator">=</span> conn<span class="token punctuation">.</span>extend<span class="token punctuation">.</span>standard<span class="token punctuation">.</span>who_am_i<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"who_am_i"</span><span class="token punctuation">,</span> ret<span class="token punctuation">)</span>

<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
<span class="token comment"># who_am_i None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>LDAP</strong> 允许无需认证的匿名登入，因为 <strong>DAP</strong> 协议最早是读取电话簿的，任何人都可以阅读（<em>但内容上会部分受限</em>），但若建立身份认证的会话，就需要 <strong>DN</strong> 和 <strong>密码</strong></p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">from</span> ldap3 <span class="token keyword">import</span> Server<span class="token punctuation">,</span> Connection<span class="token punctuation">,</span> ALL

server <span class="token operator">=</span> Server<span class="token punctuation">(</span><span class="token string">"uit.devops.local"</span><span class="token punctuation">,</span> get_info<span class="token operator">=</span>ALL<span class="token punctuation">)</span>
<span class="token comment"># conn = Connection(server, user="zhengze", password="user@dev", auto_bind=True) # 或使用 DN</span>
conn <span class="token operator">=</span> Connection<span class="token punctuation">(</span>server<span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'cn=zhengze,cn=Users,dc=uit,dc=devops,dc=local'</span><span class="token punctuation">,</span> password<span class="token operator">=</span><span class="token string">'user@dev'</span><span class="token punctuation">,</span> auto_bind<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span>

ret <span class="token operator">=</span> conn<span class="token punctuation">.</span>extend<span class="token punctuation">.</span>standard<span class="token punctuation">.</span>who_am_i<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>ret<span class="token punctuation">)</span>

<span class="token comment"># u:UIT\zhengze</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-1-查询" tabindex="-1"><a class="header-anchor" href="#_2-1-查询" aria-hidden="true">#</a> 2.1 查询</h3>
<p>可使用 <strong>上下文管理器</strong> 自动绑定，查询操作如下</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">with</span> Connection<span class="token punctuation">(</span>server<span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'cn=zhengze,cn=Users,dc=uit,dc=devops,dc=local'</span><span class="token punctuation">,</span> password<span class="token operator">=</span><span class="token string">'user@dev'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> conn<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>conn<span class="token punctuation">.</span>extend<span class="token punctuation">.</span>standard<span class="token punctuation">.</span>who_am_i<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    conn<span class="token punctuation">.</span>search<span class="token punctuation">(</span><span class="token string">'dc=uit,dc=devops,dc=local'</span><span class="token punctuation">,</span> <span class="token string">'(objectclass=user)'</span><span class="token punctuation">,</span>
                attributes<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">'name'</span><span class="token punctuation">,</span> <span class="token string">'cn'</span><span class="token punctuation">,</span> <span class="token string">'mail'</span><span class="token punctuation">,</span> <span class="token string">"description"</span><span class="token punctuation">,</span> <span class="token string">"UserAccountControl"</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>conn<span class="token punctuation">.</span>entries<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">.</span>name<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>conn<span class="token punctuation">.</span>entries<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">.</span>entry_to_json<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用 <strong>search()</strong> 查询，支持生成器方式如下</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">search_generator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">with</span> Connection<span class="token punctuation">(</span>server<span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'cn=zhengze,cn=Users,dc=uit,dc=devops,dc=local'</span><span class="token punctuation">,</span> password<span class="token operator">=</span><span class="token string">'user@dev'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> conn<span class="token punctuation">:</span>
        entry_generator <span class="token operator">=</span> conn<span class="token punctuation">.</span>extend<span class="token punctuation">.</span>standard<span class="token punctuation">.</span>paged_search<span class="token punctuation">(</span>
            search_base<span class="token operator">=</span><span class="token string">"dc=uit,dc=devops,dc=local"</span><span class="token punctuation">,</span>
            search_filter<span class="token operator">=</span><span class="token string">'(objectClass=user)'</span><span class="token punctuation">,</span>
            search_scope<span class="token operator">=</span>SUBTREE<span class="token punctuation">,</span>
            attributes<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">'cn'</span><span class="token punctuation">,</span> <span class="token string">'name'</span><span class="token punctuation">,</span> <span class="token string">'mail'</span><span class="token punctuation">,</span> <span class="token string">"description"</span><span class="token punctuation">,</span> <span class="token string">"UserAccountControl"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            paged_size<span class="token operator">=</span><span class="token number">1000</span><span class="token punctuation">,</span>
            generator<span class="token operator">=</span><span class="token boolean">True</span>
        <span class="token punctuation">)</span>
        <span class="token keyword">for</span> entry <span class="token keyword">in</span> entry_generator<span class="token punctuation">:</span>
            <span class="token keyword">if</span> <span class="token keyword">not</span> entry<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"attributes"</span><span class="token punctuation">,</span> <span class="token boolean">None</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
                <span class="token keyword">continue</span>
            <span class="token keyword">yield</span> entry<span class="token punctuation">[</span><span class="token string">'attributes'</span><span class="token punctuation">]</span>


users <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
entry <span class="token operator">=</span> search_generator<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">for</span> item <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">try</span><span class="token punctuation">:</span>
        users<span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token builtin">next</span><span class="token punctuation">(</span>entry<span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token keyword">except</span> StopIteration<span class="token punctuation">:</span>
        <span class="token keyword">break</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-2-增加" tabindex="-1"><a class="header-anchor" href="#_2-2-增加" aria-hidden="true">#</a> 2.2 增加</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


