import comp from "D:/Program/Igarashi-G.github.io/blog/.vuepress/.temp/pages/unix/虚拟机/VMware/添加磁盘.html.vue"
const data = JSON.parse("{\"path\":\"/unix/%E8%99%9A%E6%8B%9F%E6%9C%BA/VMware/%E6%B7%BB%E5%8A%A0%E7%A3%81%E7%9B%98.html\",\"title\":\"添加磁盘\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"添加磁盘\",\"date\":\"2021-03-12T00:00:00.000Z\",\"category\":[\"虚拟机\"],\"tag\":[\"VMware\"],\"description\":\"VMware 磁盘 1. 磁盘热插 正常情况下，添加磁盘后 需要重启系统 才能被内核识别，在 /dev/ 下才有对应的设备号 但是有时候不方便重启。可使用如下方法 查看所有设备的总线信息 确定磁盘在哪条总线上后使用一下命令进行总线扫描,新设备会被添加 当总线很多时使用循环对总线扫描完成热插 2. 磁盘热拔 先获取该 scsi 磁盘设备的总线号 在其中有...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"添加磁盘\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2021-03-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"悦·宝宝\\\",\\\"url\\\":\\\"https://github.com/Igarashi-G\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/unix/%E8%99%9A%E6%8B%9F%E6%9C%BA/VMware/%E6%B7%BB%E5%8A%A0%E7%A3%81%E7%9B%98.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"悦 ▪ 宝宝\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"添加磁盘\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"VMware 磁盘 1. 磁盘热插 正常情况下，添加磁盘后 需要重启系统 才能被内核识别，在 /dev/ 下才有对应的设备号 但是有时候不方便重启。可使用如下方法 查看所有设备的总线信息 确定磁盘在哪条总线上后使用一下命令进行总线扫描,新设备会被添加 当总线很多时使用循环对总线扫描完成热插 2. 磁盘热拔 先获取该 scsi 磁盘设备的总线号 在其中有...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"VMware\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-03-12T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":1.1,\"words\":330},\"filePathRelative\":\"unix/虚拟机/VMware/添加磁盘.md\",\"excerpt\":\"\\n<h3>1. 磁盘热插</h3>\\n<p>正常情况下，添加磁盘后 <strong>需要重启系统</strong> 才能被内核识别，在 <code>/dev/</code> 下才有对应的设备号</p>\\n<div class=\\\"language-shell line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"shell\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code><span class=\\\"line\\\"><span style=\\\"--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic\\\"># 使用如下命令，才会显示</span></span>\\n<span class=\\\"line\\\"><span style=\\\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\\\">$</span><span style=\\\"--shiki-light:#50A14F;--shiki-dark:#98C379\\\"> fdisk</span><span style=\\\"--shiki-light:#986801;--shiki-dark:#D19A66\\\"> -l</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
