export const data = JSON.parse("{\"key\":\"v-2d9c4133\",\"path\":\"/unix/CentOS/UDS/ufs%E6%A0%B8%E5%BF%83%E7%BB%84%E4%BB%B6.html\",\"title\":\"ufs 核心组件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"ufs 核心组件\",\"order\":3,\"summary\":\"核心组件 产品：UFS 版本：v4.0 日期：2021-10-16 摘要：本文档提供 UFS 存储系统核心组件的配置说明 1. MSS 组件 1.1 基本信息 类目 信息 说明 ------------ ------------------------------ ---------------- 核心进程 ufsmetaserver 进程路径 /usr/s\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/igarashi-blog/igarashi-blog/unix/CentOS/UDS/ufs%E6%A0%B8%E5%BF%83%E7%BB%84%E4%BB%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ufs 核心组件\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1. MSS 组件\",\"slug\":\"_1-mss-组件\",\"link\":\"#_1-mss-组件\",\"children\":[{\"level\":3,\"title\":\"1.1 基本信息\",\"slug\":\"_1-1-基本信息\",\"link\":\"#_1-1-基本信息\",\"children\":[]},{\"level\":3,\"title\":\"1.2 操作方式\",\"slug\":\"_1-2-操作方式\",\"link\":\"#_1-2-操作方式\",\"children\":[]},{\"level\":3,\"title\":\"1.3 操作类型\",\"slug\":\"_1-3-操作类型\",\"link\":\"#_1-3-操作类型\",\"children\":[]},{\"level\":3,\"title\":\"1.4 参数配置\",\"slug\":\"_1-4-参数配置\",\"link\":\"#_1-4-参数配置\",\"children\":[]}]},{\"level\":2,\"title\":\"2. CSS 组件\",\"slug\":\"_2-css-组件\",\"link\":\"#_2-css-组件\",\"children\":[{\"level\":3,\"title\":\"2.1 基本信息\",\"slug\":\"_2-1-基本信息\",\"link\":\"#_2-1-基本信息\",\"children\":[]},{\"level\":3,\"title\":\"2.2 操作方式\",\"slug\":\"_2-2-操作方式\",\"link\":\"#_2-2-操作方式\",\"children\":[]},{\"level\":3,\"title\":\"2.3 操作类型\",\"slug\":\"_2-3-操作类型\",\"link\":\"#_2-3-操作类型\",\"children\":[]},{\"level\":3,\"title\":\"2.4 参数配置\",\"slug\":\"_2-4-参数配置\",\"link\":\"#_2-4-参数配置\",\"children\":[]}]},{\"level\":2,\"title\":\"3. CLIENT 组件\",\"slug\":\"_3-client-组件\",\"link\":\"#_3-client-组件\",\"children\":[{\"level\":3,\"title\":\"3.1 基本信息\",\"slug\":\"_3-1-基本信息\",\"link\":\"#_3-1-基本信息\",\"children\":[]},{\"level\":3,\"title\":\"3.2 操作方式\",\"slug\":\"_3-2-操作方式\",\"link\":\"#_3-2-操作方式\",\"children\":[]},{\"level\":3,\"title\":\"3.3 操作类型\",\"slug\":\"_3-3-操作类型\",\"link\":\"#_3-3-操作类型\",\"children\":[]},{\"level\":3,\"title\":\"3.4 参数配置\",\"slug\":\"_3-4-参数配置\",\"link\":\"#_3-4-参数配置\",\"children\":[]},{\"level\":3,\"title\":\"3.5 应用场景\",\"slug\":\"_3-5-应用场景\",\"link\":\"#_3-5-应用场景\",\"children\":[]}]}],\"readingTime\":{\"minutes\":12.52,\"words\":3756},\"filePathRelative\":\"unix/CentOS/UDS/ufs核心组件.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
