export const data = JSON.parse("{\"key\":\"v-42da38d8\",\"path\":\"/python/%E7%94%9F%E6%80%81/RPC/%E5%88%86%E5%B8%83%E5%BC%8F%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8_Pyro.html\",\"title\":\"PYRO\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"PYRO\",\"order\":3,\"summary\":\"分布式远程调用 PYRO 可惜非异步 一、概述 1.是啥 使对象通过网络以最小的编程工作量，实现只用普通的 Python 方法调用来调 分布式计算机上运行对象的 纯 Python 库 2.用途\\r分发和集成各种资源或职责：计算（硬件）资源（cpu，存储，打印机），信息资源（数据，特权信息）和业务逻辑（部门，域）。; \\r将群集上的可用资源公开给其他计算机。; \\r\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/igarashi-blog/python/%E7%94%9F%E6%80%81/RPC/%E5%88%86%E5%B8%83%E5%BC%8F%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8_Pyro.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"是五十岚呐~\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"PYRO\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"一、概述\",\"slug\":\"一、概述\",\"link\":\"#一、概述\",\"children\":[{\"level\":3,\"title\":\"1.是啥\",\"slug\":\"_1-是啥\",\"link\":\"#_1-是啥\",\"children\":[]},{\"level\":3,\"title\":\"2.用途\",\"slug\":\"_2-用途\",\"link\":\"#_2-用途\",\"children\":[]}]},{\"level\":2,\"title\":\"二、简单使用\",\"slug\":\"二、简单使用\",\"link\":\"#二、简单使用\",\"children\":[{\"level\":3,\"title\":\"1.简单例子：\",\"slug\":\"_1-简单例子\",\"link\":\"#_1-简单例子\",\"children\":[]},{\"level\":3,\"title\":\"2.借助于 nameserver 的简单例子：\",\"slug\":\"_2-借助于-nameserver-的简单例子\",\"link\":\"#_2-借助于-nameserver-的简单例子\",\"children\":[]},{\"level\":3,\"title\":\"3.基本概念\",\"slug\":\"_3-基本概念\",\"link\":\"#_3-基本概念\",\"children\":[]}]},{\"level\":2,\"title\":\"4.名称服务器相关使用\",\"slug\":\"_4-名称服务器相关使用\",\"link\":\"#_4-名称服务器相关使用\",\"children\":[{\"level\":3,\"title\":\"1.启动名称服务器\",\"slug\":\"_1-启动名称服务器\",\"link\":\"#_1-启动名称服务器\",\"children\":[]},{\"level\":3,\"title\":\"2.与名称服务器交互\",\"slug\":\"_2-与名称服务器交互\",\"link\":\"#_2-与名称服务器交互\",\"children\":[]},{\"level\":3,\"title\":\"3.其他 cli：\",\"slug\":\"_3-其他-cli\",\"link\":\"#_3-其他-cli\",\"children\":[]}]},{\"level\":2,\"title\":\"5.客户端：远程调用对象\",\"slug\":\"_5-客户端-远程调用对象\",\"link\":\"#_5-客户端-远程调用对象\",\"children\":[{\"level\":3,\"title\":\"一、对象发现\",\"slug\":\"一、对象发现\",\"link\":\"#一、对象发现\",\"children\":[]},{\"level\":3,\"title\":\"二、调用方式\",\"slug\":\"二、调用方式\",\"link\":\"#二、调用方式\",\"children\":[]},{\"level\":3,\"title\":\"三、访问远程属性\",\"slug\":\"三、访问远程属性\",\"link\":\"#三、访问远程属性\",\"children\":[]},{\"level\":3,\"title\":\"四、序列化/自定义序列化\",\"slug\":\"四、序列化-自定义序列化\",\"link\":\"#四、序列化-自定义序列化\",\"children\":[]},{\"level\":3,\"title\":\"五、代理，连接，线程和清理\",\"slug\":\"五、代理-连接-线程和清理\",\"link\":\"#五、代理-连接-线程和清理\",\"children\":[]},{\"level\":3,\"title\":\"六、单向通话 & 批量通话\",\"slug\":\"六、单向通话-批量通话\",\"link\":\"#六、单向通话-批量通话\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.47,\"words\":2842},\"filePathRelative\":\"python/生态/RPC/分布式远程调用_Pyro.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
