import comp from "/Users/fuuka/Desktop/CODE/Igarashi-G.github.io/blog/.vuepress/.temp/pages/python/语言/多任务编程/多进程编程.html.vue"
const data = JSON.parse("{\"path\":\"/python/%E8%AF%AD%E8%A8%80/%E5%A4%9A%E4%BB%BB%E5%8A%A1%E7%BC%96%E7%A8%8B/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E7%BC%96%E7%A8%8B.html\",\"title\":\"多进程编程\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"多进程编程\",\"date\":\"2021-01-03T00:00:00.000Z\",\"category\":[\"Python\",\"多进程\"],\"tag\":[\"Python\",\"多进程\",\"subprocess\"],\"description\":\"Python 基于进程的并行计算 multiprocessing：是一个与 threading 模块类似的包，能提供本地和远程的 并发 操作（若多核那么就是 并行 操作）。它利用子进程来绕过了 GIL 锁 ，适用于 Unix 和 Windows 系统的 CPU(计算)密集型操作（且通常不依赖上次计算结果） 1. 多进程 multiprocessing ...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"多进程编程\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2021-01-03T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"悦·宝宝\\\",\\\"url\\\":\\\"https://github.com/Igarashi-G\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://igarashi-g.github.io/python/%E8%AF%AD%E8%A8%80/%E5%A4%9A%E4%BB%BB%E5%8A%A1%E7%BC%96%E7%A8%8B/%E5%A4%9A%E8%BF%9B%E7%A8%8B%E7%BC%96%E7%A8%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"悦 ▪ 宝宝\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"多进程编程\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Python 基于进程的并行计算 multiprocessing：是一个与 threading 模块类似的包，能提供本地和远程的 并发 操作（若多核那么就是 并行 操作）。它利用子进程来绕过了 GIL 锁 ，适用于 Unix 和 Windows 系统的 CPU(计算)密集型操作（且通常不依赖上次计算结果） 1. 多进程 multiprocessing ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"subprocess\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"多进程\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Python\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-03T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":13.48,\"words\":4045},\"filePathRelative\":\"python/语言/多任务编程/多进程编程.md\",\"excerpt\":\"<p><strong>Python</strong> 基于进程的并行计算</p>\\n<!--more-->\\n<p><strong>multiprocessing</strong>：是一个与 <a href=\\\"/back_end/python/base/%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6/%E5%A4%9A%E7%BA%BF%E7%A8%8B%E7%BC%96%E7%A8%8B#%E5%9F%BA%E4%BA%8E%E7%BA%BF%E7%A8%8B%E7%9A%84%E5%B9%B6%E5%8F%91\\\">threading</a> 模块类似的包，能提供本地和远程的 <a href=\\\"/back_end/python/base/%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6/%E8%BF%9B%E7%A8%8B#12-%E5%B9%B6%E5%8F%91\\\">并发</a> 操作（若多核那么就是 <a href=\\\"/back_end/python/base/%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6/%E8%BF%9B%E7%A8%8B#11-%E5%B9%B6%E8%A1%8C\\\">并行</a> 操作）。它利用子进程来绕过了 <a href=\\\"/back_end/python/base/%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6/%E5%A4%9A%E7%BA%BF%E7%A8%8B%E7%BC%96%E7%A8%8B#%E5%9F%BA%E4%BA%8E%E7%BA%BF%E7%A8%8B%E7%9A%84%E5%B9%B6%E5%8F%91\\\">GIL 锁</a> ，适用于 Unix 和 Windows 系统的 <strong>CPU</strong>(计算)密集型操作（且通常不依赖上次计算结果）</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
